### ISSUE TITLE
Some Parameters ignored

### ISSUE THREAD

**Issue by sascha224** [EvotecIT/PSPasswordExpiryNotifications#1]
Tested it with the sample script, and it works so far. But I have some trouble getting it work with german chartable, the german umlauts are scrambled. In the sample script, I configured "EmailEncoding =" UTF8"" instead of Unicode, but that doesn't change anything.

The other thing is that FontSettings seem to be ignored, the mail comes with Times New Roman 12pt (tried it with Arial or Calibri).

**Comment by PrzemyslawKlys** [comment]
You may need to change whole .ps1 file encoding to required encoding. The one you run. Try that and let me know

**Comment by PrzemyslawKlys** [comment]
Also if possible check html source in email and paste it over

**Comment by sascha224** [comment]
> 
> 
> You may need to change whole .ps1 file encoding to required encoding. The one you run. Try that and let me know

You mean the script file itself? The file is already encoded in UTF8.

**Comment by sascha224** [comment]
`<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><style>
        BODY {
            background-color: white;
            font-family: Calibri;
            font-size: 10pt;
        }

        TABLE {
            border-width: 1px;
            border-style: solid;
            border-color: black;
            border-collapse: collapse;
            font-family: Calibri;
            font-size: 10pt;
        }

        TH {
            border-width: 1px;
            padding: 3px;
            border-style: solid;
            border-color: black;
            background-color: #00297A;
            color: white;
            font-family: Calibri;
            font-size: 10pt;
        }
        TR {
            font-family: Calibri;
            font-size: 10pt;
        }

        TD {
            border-width: 1px;
            padding-right: 2px;
            padding-left: 2px;
            padding-top: 0px;
            padding-bottom: 0px;
            border-style: solid;
            border-color: black;
            background-color: white;
            font-family: Calibri;
            font-size: 10pt;
        }

        H2 {
            font-family: Calibri;
            font-size: 12pt;
        }

        P {
            font-family: Calibri;
            font-size: 10pt;
        }
    </style><a style="text-decoration:none" href="https://test.com" class="clink logo-container"><img width="200" src="https://test.com/logo.png" border="0" class="company-logo" alt="company-logo"></a><br><br>    Hallo <b>Walter Hans</b>,<br>    Ihr Windows-<i>Passwort</i> wird in 10 Tagen ablaufen.<br><br>    Um das <i>Passwort</i> zu wechseln:<br>    - <span style="color:Blue">CTRL&#43;ALT&#43;DEL</span> -&gt; <i>Kennwort</i> Ã¤ndern...<br><br>    Wenn Sie Ihr <i>Passwort</i> vergessen haben und es <span style="color:Red">zurÃ¼cksetzen</span> mÃ¶chten, klicken Sie bitte <span style="color:Red"><a href="https://passwordreset.microsoftonline.com/">hier</a></span>.<br>    Bei Problemen kontaktieren Sie bitte den <u>IT-Support</u> <span style="color:Red"><a href="http://helpdesk.test.com:81">Service Portal</a></span> , E-Mail <span style="color:Red"><a href="mailto:it-support@test.com?subject=I need help with my password">IT-Support</a></span>.<br><br>    Oder kontaktieren Sie den <u>IT-Support</u> telefonisch Ã¼ber die Kurzwahl <span style="color:Green">555</span>.<br><br>    Freundliche GrÃ¼sse<br>    <u>IT-Support</u><br>	MÃ¼ller Group`

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/45556937-c48e2a80-b83c-11e8-9343-db4a70b46d60.png)

You may want to change it to UTF16 maybe. Did you solve your problem that you closed this?

**Comment by PrzemyslawKlys** [comment]
As for the fonts... it seems it's added properly into email. Can you verify those fonts have same names in German systems? Maybe that''s why they don't work?

**Comment by sascha224** [comment]
> You may want to change it to UTF16 maybe. Did you solve your problem that you closed this?

Changing the encoding of the PS1 file to UTF-16 LE did it, the German Umlauts are back :-)

**Comment by PrzemyslawKlys** [comment]
And fonts?

**Comment by sascha224** [comment]
> 
> 
> As for the fonts... it seems it's added properly into email. Can you verify those fonts have same names in German systems? Maybe that''s why they don't work?

Fonts are still broken... The font names are the same in german, and those names work with other applications that send HTML mails via SMTP

**Comment by PrzemyslawKlys** [comment]
That's weird thou because HTML wise it looks ok. Which Client? Outlook ?

**Comment by sascha224** [comment]
Yes, Outlook. But I remember that we had a similar problem with our ERP system. We had to embed the body text with <span style='font family:Calibri'> tags to set the font correctly for Outlook. Don't invest too much time into that issue, I think Outlook is the problem here...

**Comment by sascha224** [comment]
Yes, Outlook. But I remember that we had a similar problem with our ERP system. We had to embed the body text with <span style='font family:Calibri'> tags to set the font correctly for Outlook. Don't invest too much time into that issue, I think Outlook is the problem here...

**Comment by sascha224** [comment]
Built a workaround for us with setting a `<span style='font-family:Calibri'>` in the Mail template text.

**Comment by PrzemyslawKlys** [comment]
Ok. It's weird because I use Outlook, my Clients use Outlook and this basically works just fine.

**Comment by PrzemyslawKlys** [comment]
please test new version. I may have fixed this issue without using span style.

**Comment by PrzemyslawKlys** [comment]
you need to update both:

```
Update-Module PSSharedGoods
Update-Module PSPasswordExpiryNotifications
```
