### ISSUE TITLE
Sending to default email doesnt work

### ISSUE THREAD

**Issue by MikeAtRogers** [EvotecIT/PSPasswordExpiryNotifications#2]
I setup everything and I get the admin reports.
I have now set 
RemindersDisplayOnly = $false # prevents sending any emails (good for testing) - including managers

But when I run the script I get:

[2019-01-07 09:11:14][i] Sending email to users is disabled. Sending email to default value: mike@xxx.xxx ...Send-Email : A parameter cannot be found that matches parameter name 'ReportOptions'.
At C:\Program Files\WindowsPowerShell\Modules\PSPasswordExpiryNotifications\0.7\Public\Start-PasswordExpiryCheck.ps1:42 char:108
+ ... rameters $EmailParameters -Body $TemporaryBody -ReportOptions $Displa ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Send-Email], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Send-Email
 
Failed!

**Comment by PrzemyslawKlys** [comment]
Right. I've not been using it for a while and seems that when I updated PSSharedGood I forgot about this module. It uses most likely some old version of it. Please give me some time to fix this. I'll report back, hopefully, today with the new version.

**Comment by MikeAtRogers** [comment]
Thanks for the quick update!
I appreciate the work that went into this, look like a great module!

**Comment by PrzemyslawKlys** [comment]
```
Update-Module PSSharedGoods
Update-Module PSPasswordExpiryNotifications
```

Give this a go. You need to update both as part of the stuff is in the shared module. I fixed some small issues here and there while I was at it.

**Comment by MikeAtRogers** [comment]
Thank you, works fine now!
