### ISSUE TITLE
Unable to send email using Office365

### ISSUE THREAD

**Issue by TravelingLex** [EvotecIT/PSPasswordExpiryNotifications#3]
I am attempting to send email through direct send with Office365 (contoso-com.mail.protection.outlook.com). I have configured the email servers correctly but receive this error when attempting to send:

Error: Exception calling "Send" with "1" argument(s): "Transaction failed. The server response was: 5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message.

**Comment by PrzemyslawKlys** [comment]
You sure its correct? Seems like you’re trying to sendas another person. Care to show the config file (without critical data thou but with subsitute that is somewhat making sense). I use Office 365 all the time.

**Comment by TravelingLex** [comment]
Here is my EmailParameters config. I've removed my critical info for contoso.com: 

$EmailParameters = @{
    EmailFrom = "no-reply@contoso.com"
    EmailTo = "alex.meyer@contoso.com" #
    EmailCC = ""
    EmailBCC = ""
    EmailReplyTo = "helpdesk@contoso.com"
    EmailServer = "contoso-com.mail.protection.outlook.com"
    EmailServerPassword = ""
    EmailServerPort = "25"
    EmailServerLogin = ""
    EmailServerEnableSSL = 1
    EmailEncoding = "Unicode"
    EmailSubject = "[Password Expiring] Your password will expire on <<DateExpiry>> (<<TimeToExpire>> days)"
    EmailPriority = "Normal" # Normal, High

**Comment by PrzemyslawKlys** [comment]
You need to fill in login/password and port should be 587

**Comment by TravelingLex** [comment]
I'm not able to use direct send with this? Thats fine, I just thought I would be able to do that.

**Comment by PrzemyslawKlys** [comment]
Direct send as in as relay? You can but most likely needs some config change. I use it via relay with Exchange2013 but pretty sure o365 requires some preparations.

**Comment by PrzemyslawKlys** [comment]
In other words have you ever sent email thru o365 that way? If so Ill take a look but pretty sure its not that easy.

**Comment by TravelingLex** [comment]
Yes I've sent it through using Office 365 both authenticated and unauthenticated. I've updated the script to include authentication: Error: Exception calling "Send" with "1" argument(s): "Failure sending mail."

**Comment by TravelingLex** [comment]
Following steps outlined here: https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3 

I used both the first and second option but receive the first error both times.

**Comment by TravelingLex** [comment]
I've decided to just relay off my internal SMTP server.

Thanks for your help and quick reply!
